---
- name: Create nginx config
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ site_name }}"
  notify: restart nginx

- name: Link nginx config
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ site_name }}"
    state: link
  notify: restart nginx
